export const ROUTES = {
  TOP: "/",
  HOME: "/home",
  HOME_TESTREAD: "home/testRead",
  FRIEND: "/friend",
  NEWS: "/news",
  MYPAGE: "/mypage",
  PROFILE_UPDATE: "/mypage/profileUpdate",
  CARD_CREATE: "mypage/cardCreate",
  CARD_UPDATE: "mypage/cardUpdate",
  MYPAGE_TESTREAD: "mypage/testRead",
  TEST_CREATE: "mypage/testCreate",
  TARGET_UPSERT: "mypage/targetUpsert",
  CONTACT: "/contact",
  LOGIN: "/login",
  REGISTER: "/register",
  PERSONAL: "/personal",
} as const;
