// 1000: ⚪︎
// 1001: ×
// 1002: 解答する必要が無い問題

import { Subject } from "@/type/testType";

export const testStructureDatas = [
  {
    subject: Subject.READING,
    year: 2015,
    maxScore: 200,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 2, correctAnswer: 2 },
          { questionNumber: 2, score: 2, correctAnswer: 1 },
          { questionNumber: 3, score: 2, correctAnswer: 1 },
          { questionNumber: 4, score: 2, correctAnswer: 2 },
          { questionNumber: 5, score: 2, correctAnswer: 4 },
          { questionNumber: 6, score: 2, correctAnswer: 4 },
          { questionNumber: 7, score: 2, correctAnswer: 3 },
        ],
        sectionTotal: { score: 14 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 8, score: 2, correctAnswer: 1 },
          { questionNumber: 9, score: 2, correctAnswer: 3 },
          { questionNumber: 10, score: 2, correctAnswer: 3 },
          { questionNumber: 11, score: 2, correctAnswer: 2 },
          { questionNumber: 12, score: 2, correctAnswer: 1 },
          { questionNumber: 13, score: 2, correctAnswer: 3 },
          { questionNumber: 14, score: 2, correctAnswer: 1 },
          { questionNumber: 15, score: 2, correctAnswer: 4 },
          { questionNumber: 16, score: 2, correctAnswer: 2 },
          { questionNumber: 17, score: 2, correctAnswer: 4 },
          { questionNumber: 18, score: 4, correctAnswer: 5 },
          { questionNumber: 19, score: null, correctAnswer: 6 },
          { questionNumber: 20, score: 4, correctAnswer: 5 },
          { questionNumber: 21, score: null, correctAnswer: 1 },
          { questionNumber: 22, score: 4, correctAnswer: 4 },
          { questionNumber: 23, score: null, correctAnswer: 5 },
          { questionNumber: 24, score: 4, correctAnswer: 7 },
          { questionNumber: 25, score: 4, correctAnswer: 6 },
          { questionNumber: 26, score: 4, correctAnswer: 1 },
        ],
        sectionTotal: { score: 44 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 27, score: 4, correctAnswer: 4 },
          { questionNumber: 28, score: 4, correctAnswer: 2 },
          { questionNumber: 29, score: 5, correctAnswer: 2 },
          { questionNumber: 30, score: 5, correctAnswer: 4 },
          { questionNumber: 31, score: 5, correctAnswer: 1 },
          { questionNumber: 32, score: 6, correctAnswer: 2 },
          { questionNumber: 33, score: 6, correctAnswer: 2 },
          { questionNumber: 34, score: 6, correctAnswer: 3 },
        ],
        sectionTotal: { score: 41 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 35, score: 5, correctAnswer: 4 },
          { questionNumber: 36, score: 5, correctAnswer: 1 },
          { questionNumber: 37, score: 5, correctAnswer: 2 },
          { questionNumber: 38, score: 5, correctAnswer: 2 },
          { questionNumber: 39, score: 5, correctAnswer: 2 },
          { questionNumber: 40, score: 5, correctAnswer: 3 },
          { questionNumber: 41, score: 5, correctAnswer: 1 },
        ],
        sectionTotal: { score: 35 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 42, score: 6, correctAnswer: 3 },
          { questionNumber: 43, score: 6, correctAnswer: 3 },
          { questionNumber: 44, score: 6, correctAnswer: 4 },
          { questionNumber: 45, score: 6, correctAnswer: 4 },
          { questionNumber: 46, score: 6, correctAnswer: 4 },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 6,
        questions: [
          { questionNumber: 47, score: 6, correctAnswer: 4 },
          { questionNumber: 48, score: 6, correctAnswer: 2 },
          { questionNumber: 49, score: 6, correctAnswer: 2 },
          { questionNumber: 50, score: 6, correctAnswer: 2 },
          { questionNumber: 51, score: 6, correctAnswer: 1 },
          { questionNumber: 52, score: 6, correctAnswer: 3 },
          { questionNumber: 53, score: null, correctAnswer: 1 },
          { questionNumber: 54, score: null, correctAnswer: 2 },
          { questionNumber: 55, score: null, correctAnswer: 4 },
        ],
        sectionTotal: { score: 36 },
      },
    ],
  },

  {
    subject: Subject.READING,
    year: 2016,
    maxScore: 200,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 2, correctAnswer: 2 },
          { questionNumber: 2, score: 2, correctAnswer: 4 },
          { questionNumber: 3, score: 2, correctAnswer: 2 },
          { questionNumber: 4, score: 2, correctAnswer: 3 },
          { questionNumber: 5, score: 2, correctAnswer: 3 },
          { questionNumber: 6, score: 2, correctAnswer: 4 },
          { questionNumber: 7, score: 2, correctAnswer: 1 },
        ],
        sectionTotal: { score: 14 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 8, score: 2, correctAnswer: 1 },
          { questionNumber: 9, score: 2, correctAnswer: 1 },
          { questionNumber: 10, score: 2, correctAnswer: 2 },
          { questionNumber: 11, score: 2, correctAnswer: 4 },
          { questionNumber: 12, score: 2, correctAnswer: 2 },
          { questionNumber: 13, score: 2, correctAnswer: 1 },
          { questionNumber: 14, score: 2, correctAnswer: 4 },
          { questionNumber: 15, score: 2, correctAnswer: 3 },
          { questionNumber: 16, score: 2, correctAnswer: 1 },
          { questionNumber: 17, score: 2, correctAnswer: 4 },
          { questionNumber: 18, score: 4, correctAnswer: 5 },
          { questionNumber: 19, score: 4, correctAnswer: 1 },
          { questionNumber: 20, score: 4, correctAnswer: 3 },
          { questionNumber: 21, score: 4, correctAnswer: 5 },
          { questionNumber: 22, score: 4, correctAnswer: 4 },
          { questionNumber: 23, score: 4, correctAnswer: 6 },
          { questionNumber: 24, score: 4, correctAnswer: 2 },
          { questionNumber: 25, score: 4, correctAnswer: 2 },
          { questionNumber: 26, score: 4, correctAnswer: 4 },
        ],
        sectionTotal: { score: 44 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 27, score: 4, correctAnswer: 4 },
          { questionNumber: 28, score: 4, correctAnswer: 2 },
          { questionNumber: 29, score: 5, correctAnswer: 1 },
          { questionNumber: 30, score: 5, correctAnswer: 2 },
          { questionNumber: 31, score: 5, correctAnswer: 1 },
          { questionNumber: 32, score: 6, correctAnswer: 4 },
          { questionNumber: 33, score: 6, correctAnswer: 4 },
          { questionNumber: 34, score: 6, correctAnswer: 1 },
        ],
        sectionTotal: { score: 41 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 35, score: 5, correctAnswer: 2 },
          { questionNumber: 36, score: 5, correctAnswer: 1 },
          { questionNumber: 37, score: 5, correctAnswer: 3 },
          { questionNumber: 38, score: 5, correctAnswer: 2 },
          { questionNumber: 39, score: 5, correctAnswer: 2 },
          { questionNumber: 40, score: 5, correctAnswer: 3 },
          { questionNumber: 41, score: 5, correctAnswer: 1 },
        ],
        sectionTotal: { score: 35 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 42, score: 6, correctAnswer: 2 },
          { questionNumber: 43, score: 6, correctAnswer: 3 },
          { questionNumber: 44, score: 6, correctAnswer: 2 },
          { questionNumber: 45, score: 6, correctAnswer: 3 },
          { questionNumber: 46, score: 6, correctAnswer: 2 },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 6,
        questions: [
          { questionNumber: 47, score: 6, correctAnswer: 1 },
          { questionNumber: 48, score: 6, correctAnswer: 3 },
          { questionNumber: 49, score: 6, correctAnswer: 1 },
          { questionNumber: 50, score: 6, correctAnswer: 3 },
          { questionNumber: 51, score: 6, correctAnswer: 3 },
          { questionNumber: 52, score: 6, correctAnswer: 3 },
          { questionNumber: 53, score: 6, correctAnswer: 1 },
          { questionNumber: 54, score: 6, correctAnswer: 4 },
          { questionNumber: 55, score: 6, correctAnswer: 2 },
        ],
        sectionTotal: { score: 36 },
      },
    ],
  },

  {
    subject: Subject.READING,
    year: 2017,
    maxScore: 200,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 2, correctAnswer: 4 },
          { questionNumber: 2, score: 2, correctAnswer: 3 },
          { questionNumber: 3, score: 2, correctAnswer: 4 },
          { questionNumber: 4, score: 2, correctAnswer: 2 },
          { questionNumber: 5, score: 2, correctAnswer: 1 },
          { questionNumber: 6, score: 2, correctAnswer: 2 },
          { questionNumber: 7, score: 2, correctAnswer: 1 },
        ],
        sectionTotal: { score: 14 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 8, score: 2, correctAnswer: 1 },
          { questionNumber: 9, score: 2, correctAnswer: 2 },
          { questionNumber: 10, score: 2, correctAnswer: 4 },
          { questionNumber: 11, score: 2, correctAnswer: 1 },
          { questionNumber: 12, score: 2, correctAnswer: 2 },
          { questionNumber: 13, score: 2, correctAnswer: 3 },
          { questionNumber: 14, score: 2, correctAnswer: 4 },
          { questionNumber: 15, score: 2, correctAnswer: 1 },
          { questionNumber: 16, score: 2, correctAnswer: 3 },
          { questionNumber: 17, score: 2, correctAnswer: 1 },
          { questionNumber: 18, score: 4, correctAnswer: 2 },
          { questionNumber: 19, score: 4, correctAnswer: 6 },
          { questionNumber: 20, score: 4, correctAnswer: 5 },
          { questionNumber: 21, score: 4, correctAnswer: 1 },
          { questionNumber: 22, score: 4, correctAnswer: 6 },
          { questionNumber: 23, score: 4, correctAnswer: 2 },
          { questionNumber: 24, score: 4, correctAnswer: 5 },
          { questionNumber: 25, score: 4, correctAnswer: 2 },
          { questionNumber: 26, score: 4, correctAnswer: 7 },
        ],
        sectionTotal: { score: 44 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 27, score: 4, correctAnswer: 2 },
          { questionNumber: 28, score: 4, correctAnswer: 3 },
          { questionNumber: 29, score: 5, correctAnswer: 3 },
          { questionNumber: 30, score: 5, correctAnswer: 2 },
          { questionNumber: 31, score: 5, correctAnswer: 3 },
          { questionNumber: 32, score: 6, correctAnswer: 3 },
          { questionNumber: 33, score: 6, correctAnswer: 4 },
          { questionNumber: 34, score: 6, correctAnswer: 2 },
        ],
        sectionTotal: { score: 41 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 35, score: 5, correctAnswer: 3 },
          { questionNumber: 36, score: 5, correctAnswer: 1 },
          { questionNumber: 37, score: 5, correctAnswer: 4 },
          { questionNumber: 38, score: 5, correctAnswer: 2 },
          { questionNumber: 39, score: 5, correctAnswer: 4 },
          { questionNumber: 40, score: 5, correctAnswer: 2 },
          { questionNumber: 41, score: 5, correctAnswer: 4 },
        ],
        sectionTotal: { score: 35 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 42, score: 6, correctAnswer: 1 },
          { questionNumber: 43, score: 6, correctAnswer: 2 },
          { questionNumber: 44, score: 6, correctAnswer: 4 },
          { questionNumber: 45, score: 6, correctAnswer: 1 },
          { questionNumber: 46, score: 6, correctAnswer: 2 },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 6,
        questions: [
          { questionNumber: 47, score: 6, correctAnswer: 4 },
          { questionNumber: 48, score: 6, correctAnswer: 2 },
          { questionNumber: 49, score: 6, correctAnswer: 4 },
          { questionNumber: 50, score: 6, correctAnswer: 4 },
          { questionNumber: 51, score: 6, correctAnswer: 1 },
          { questionNumber: 52, score: 6, correctAnswer: 4 },
          { questionNumber: 53, score: 6, correctAnswer: 2 },
          { questionNumber: 54, score: 6, correctAnswer: 3 },
          { questionNumber: 55, score: 6, correctAnswer: 1 },
        ],
        sectionTotal: { score: 36 },
      },
    ],
  },

  {
    subject: Subject.READING,
    year: 2018,
    maxScore: 200,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 2, correctAnswer: 4 },
          { questionNumber: 2, score: 2, correctAnswer: 3 },
          { questionNumber: 3, score: 2, correctAnswer: 2 },
          { questionNumber: 4, score: 2, correctAnswer: 1 },
          { questionNumber: 5, score: 2, correctAnswer: 4 },
          { questionNumber: 6, score: 2, correctAnswer: 3 },
          { questionNumber: 7, score: 2, correctAnswer: 2 },
        ],
        sectionTotal: { score: 14 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 8, score: 2, correctAnswer: 3 },
          { questionNumber: 9, score: 2, correctAnswer: 2 },
          { questionNumber: 10, score: 2, correctAnswer: 1 },
          { questionNumber: 11, score: 2, correctAnswer: 4 },
          { questionNumber: 12, score: 2, correctAnswer: 1 },
          { questionNumber: 13, score: 2, correctAnswer: 3 },
          { questionNumber: 14, score: 2, correctAnswer: 1 },
          { questionNumber: 15, score: 2, correctAnswer: 3 },
          { questionNumber: 16, score: 2, correctAnswer: 3 },
          { questionNumber: 17, score: 2, correctAnswer: 3 },
          { questionNumber: 18, score: 2, correctAnswer: 3 },
          { questionNumber: 19, score: 4, correctAnswer: 2 },
          { questionNumber: 20, score: 4, correctAnswer: 4 },
          { questionNumber: 21, score: 4, correctAnswer: 2 },
          { questionNumber: 22, score: 4, correctAnswer: 3 },
          { questionNumber: 23, score: 4, correctAnswer: 2 },
          { questionNumber: 24, score: 5, correctAnswer: 2 },
          { questionNumber: 25, score: 5, correctAnswer: 4 },
          { questionNumber: 26, score: 5, correctAnswer: 8 },
        ],
        sectionTotal: { score: 47 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 27, score: 5, correctAnswer: 2 },
          { questionNumber: 28, score: 5, correctAnswer: 3 },
          { questionNumber: 29, score: 5, correctAnswer: 2 },
          { questionNumber: 30, score: 6, correctAnswer: 1 },
          { questionNumber: 31, score: 6, correctAnswer: 3 },
          { questionNumber: 32, score: 6, correctAnswer: 4 },
        ],
        sectionTotal: { score: 23 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 33, score: 5, correctAnswer: 2 },
          { questionNumber: 34, score: 5, correctAnswer: 3 },
          { questionNumber: 35, score: 5, correctAnswer: 2 },
          { questionNumber: 36, score: 5, correctAnswer: 4 },
          { questionNumber: 37, score: 5, correctAnswer: 4 },
          { questionNumber: 38, score: 5, correctAnswer: 2 },
          { questionNumber: 39, score: 5, correctAnswer: 3 },
          { questionNumber: 40, score: 5, correctAnswer: 4 },
        ],
        sectionTotal: { score: 40 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 41, score: 6, correctAnswer: 3 },
          { questionNumber: 42, score: 6, correctAnswer: 2 },
          { questionNumber: 43, score: 6, correctAnswer: 2 },
          { questionNumber: 44, score: 6, correctAnswer: 1 },
          { questionNumber: 45, score: 6, correctAnswer: 3 },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 6,
        questions: [
          { questionNumber: 46, score: 6, correctAnswer: 4 },
          { questionNumber: 47, score: 6, correctAnswer: 2 },
          { questionNumber: 48, score: 6, correctAnswer: 1 },
          { questionNumber: 49, score: 6, correctAnswer: 1 },
          { questionNumber: 50, score: 6, correctAnswer: 2 },
          { questionNumber: 51, score: 6, correctAnswer: 4 },
          { questionNumber: 52, score: null, correctAnswer: 2 },
          { questionNumber: 53, score: null, correctAnswer: 3 },
          { questionNumber: 54, score: null, correctAnswer: 1 },
        ],
        sectionTotal: { score: 36 },
      },
    ],
  },

  {
    subject: Subject.READING,
    year: 2019,
    maxScore: 200,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 2, correctAnswer: 2 },
          { questionNumber: 2, score: 2, correctAnswer: 1 },
          { questionNumber: 3, score: 2, correctAnswer: 2 },
          { questionNumber: 4, score: 2, correctAnswer: 3 },
          { questionNumber: 5, score: 2, correctAnswer: 2 },
          { questionNumber: 6, score: 2, correctAnswer: 2 },
          { questionNumber: 7, score: 2, correctAnswer: 1 },
        ],
        sectionTotal: { score: 14 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 8, score: 2, correctAnswer: 2 },
          { questionNumber: 9, score: 2, correctAnswer: 3 },
          { questionNumber: 10, score: 2, correctAnswer: 1 },
          { questionNumber: 11, score: 2, correctAnswer: 2 },
          { questionNumber: 12, score: 2, correctAnswer: 4 },
          { questionNumber: 13, score: 2, correctAnswer: 3 },
          { questionNumber: 14, score: 2, correctAnswer: 3 },
          { questionNumber: 15, score: 2, correctAnswer: 2 },
          { questionNumber: 16, score: 2, correctAnswer: 4 },
          { questionNumber: 17, score: 2, correctAnswer: 4 },
          { questionNumber: 18, score: 4, correctAnswer: 2 },
          { questionNumber: 19, score: 4, correctAnswer: 5 },
          { questionNumber: 20, score: 4, correctAnswer: 6 },
          { questionNumber: 21, score: 4, correctAnswer: 2 },
          { questionNumber: 22, score: 4, correctAnswer: 2 },
          { questionNumber: 23, score: 4, correctAnswer: 6 },
          { questionNumber: 24, score: 5, correctAnswer: 6 },
          { questionNumber: 25, score: 5, correctAnswer: 2 },
          { questionNumber: 26, score: 5, correctAnswer: 3 },
        ],
        sectionTotal: { score: 47 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 27, score: 5, correctAnswer: 1 },
          { questionNumber: 28, score: 5, correctAnswer: 2 },
          { questionNumber: 29, score: 5, correctAnswer: 4 },
          { questionNumber: 30, score: 6, correctAnswer: 1 },
          { questionNumber: 31, score: 6, correctAnswer: 3 },
          { questionNumber: 32, score: 6, correctAnswer: 3 },
        ],
        sectionTotal: { score: 33 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 33, score: 5, correctAnswer: 2 },
          { questionNumber: 34, score: 5, correctAnswer: 4 },
          { questionNumber: 35, score: 5, correctAnswer: 2 },
          { questionNumber: 36, score: 5, correctAnswer: 3 },
          { questionNumber: 37, score: 5, correctAnswer: 3 },
          { questionNumber: 38, score: 5, correctAnswer: 2 },
          { questionNumber: 39, score: 5, correctAnswer: 2 },
          { questionNumber: 40, score: 5, correctAnswer: 2 },
        ],
        sectionTotal: { score: 40 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 41, score: 6, correctAnswer: 1 },
          { questionNumber: 42, score: 6, correctAnswer: 2 },
          { questionNumber: 43, score: 6, correctAnswer: 1 },
          { questionNumber: 44, score: 6, correctAnswer: 3 },
          { questionNumber: 45, score: 6, correctAnswer: 3 },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 6,
        questions: [
          { questionNumber: 46, score: 6, correctAnswer: 2 },
          { questionNumber: 47, score: 6, correctAnswer: 3 },
          { questionNumber: 48, score: 6, correctAnswer: 4 },
          { questionNumber: 49, score: 6, correctAnswer: 1 },
          { questionNumber: 50, score: 6, correctAnswer: 4 },
          { questionNumber: 51, score: 6, correctAnswer: 1 },
          { questionNumber: 52, score: 6, correctAnswer: 4 },
          { questionNumber: 53, score: 6, correctAnswer: 2 },
          { questionNumber: 54, score: 6, correctAnswer: 3 },
        ],
        sectionTotal: { score: 36 },
      },
    ],
  },

  {
    subject: Subject.READING,
    year: 2020,
    maxScore: 200,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 2, correctAnswer: 2 },
          { questionNumber: 2, score: 2, correctAnswer: 3 },
          { questionNumber: 3, score: 2, correctAnswer: 4 },
          { questionNumber: 4, score: 2, correctAnswer: 2 },
          { questionNumber: 5, score: 2, correctAnswer: 1 },
          { questionNumber: 6, score: 2, correctAnswer: 1 },
          { questionNumber: 7, score: 2, correctAnswer: 2 },
        ],
        sectionTotal: { score: 14 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 8, score: 2, correctAnswer: 3 },
          { questionNumber: 9, score: 2, correctAnswer: 1 },
          { questionNumber: 10, score: 2, correctAnswer: 3 },
          { questionNumber: 11, score: 2, correctAnswer: 3 },
          { questionNumber: 12, score: 2, correctAnswer: 1 },
          { questionNumber: 13, score: 2, correctAnswer: 1 },
          { questionNumber: 14, score: 2, correctAnswer: 1 },
          { questionNumber: 15, score: 2, correctAnswer: 4 },
          { questionNumber: 16, score: 2, correctAnswer: 2 },
          { questionNumber: 17, score: 2, correctAnswer: 1 },
          { questionNumber: 18, score: 4, correctAnswer: 4 },
          { questionNumber: 19, score: 4, correctAnswer: 2 },
          { questionNumber: 20, score: 4, correctAnswer: 4 },
          { questionNumber: 21, score: 4, correctAnswer: 3 },
          { questionNumber: 22, score: 4, correctAnswer: 5 },
          { questionNumber: 23, score: 4, correctAnswer: 2 },
          { questionNumber: 24, score: 5, correctAnswer: 3 },
          { questionNumber: 25, score: 5, correctAnswer: 1 },
          { questionNumber: 26, score: 5, correctAnswer: 3 },
        ],
        sectionTotal: { score: 47 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 27, score: 5, correctAnswer: 2 },
          { questionNumber: 28, score: 5, correctAnswer: 2 },
          { questionNumber: 29, score: 5, correctAnswer: 2 },
          { questionNumber: 30, score: 6, correctAnswer: 3 },
          { questionNumber: 31, score: 6, correctAnswer: 3 },
          { questionNumber: 32, score: 6, correctAnswer: 4 },
        ],
        sectionTotal: { score: 33 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 33, score: 5, correctAnswer: 4 },
          { questionNumber: 34, score: 5, correctAnswer: 4 },
          { questionNumber: 35, score: 5, correctAnswer: 2 },
          { questionNumber: 36, score: 5, correctAnswer: 4 },
          { questionNumber: 37, score: 5, correctAnswer: 1 },
          { questionNumber: 38, score: 5, correctAnswer: 1 },
          { questionNumber: 39, score: 5, correctAnswer: 2 },
          { questionNumber: 40, score: 5, correctAnswer: 4 },
        ],
        sectionTotal: { score: 40 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 41, score: 6, correctAnswer: 1 },
          { questionNumber: 42, score: 6, correctAnswer: 4 },
          { questionNumber: 43, score: 6, correctAnswer: 4 },
          { questionNumber: 44, score: 6, correctAnswer: 2 },
          { questionNumber: 45, score: 6, correctAnswer: 2 },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 6,
        questions: [
          { questionNumber: 46, score: 6, correctAnswer: 1 },
          { questionNumber: 47, score: 6, correctAnswer: 3 },
          { questionNumber: 48, score: 6, correctAnswer: 2 },
          { questionNumber: 49, score: 6, correctAnswer: 4 },
          { questionNumber: 50, score: 6, correctAnswer: 2 },
          { questionNumber: 51, score: 6, correctAnswer: 2 },
          { questionNumber: 52, score: 6, correctAnswer: 4 },
          { questionNumber: 53, score: 6, correctAnswer: 3 },
          { questionNumber: 54, score: 6, correctAnswer: 1 },
        ],
        sectionTotal: { score: 36 },
      },
    ],
  },

  {
    subject: Subject.MATH1A,
    year: 2015,
    maxScore: 100,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 5, correctAnswer: null },
          { questionNumber: 2, score: 5, correctAnswer: null },
          { questionNumber: 3, score: 5, correctAnswer: null },
          { questionNumber: 4, score: 2, correctAnswer: null },
          { questionNumber: 5, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 6, score: 4, correctAnswer: null },
          { questionNumber: 7, score: 3, correctAnswer: null },
          { questionNumber: 8, score: 3, correctAnswer: null },
          { questionNumber: 9, score: 3, correctAnswer: null },
          { questionNumber: 10, score: 3, correctAnswer: null },
          { questionNumber: 11, score: 3, correctAnswer: null },
          { questionNumber: 12, score: 3, correctAnswer: null },
          { questionNumber: 13, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 25 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 14, score: 3, correctAnswer: null },
          { questionNumber: 15, score: 4, correctAnswer: null },
          { questionNumber: 16, score: 6, correctAnswer: null },
          { questionNumber: 17, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 15 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 18, score: 3, correctAnswer: null },
          { questionNumber: 19, score: 2, correctAnswer: null },
          { questionNumber: 20, score: 3, correctAnswer: null },
          { questionNumber: 21, score: 3, correctAnswer: null },
          { questionNumber: 22, score: 2, correctAnswer: null },
          { questionNumber: 23, score: 2, correctAnswer: null },
          { questionNumber: 24, score: 2, correctAnswer: null },
          { questionNumber: 25, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 26, score: 3, correctAnswer: null },
          { questionNumber: 27, score: 3, correctAnswer: null },
          { questionNumber: 28, score: 3, correctAnswer: null },
          { questionNumber: 29, score: 3, correctAnswer: null },
          { questionNumber: 30, score: 2, correctAnswer: null },
          { questionNumber: 31, score: 2, correctAnswer: null },
          { questionNumber: 32, score: 4, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 6,
        questions: [
          { questionNumber: 33, score: 3, correctAnswer: null },
          { questionNumber: 34, score: 3, correctAnswer: null },
          { questionNumber: 35, score: 3, correctAnswer: null },
          { questionNumber: 36, score: 4, correctAnswer: null },
          { questionNumber: 37, score: 4, correctAnswer: null },
          { questionNumber: 38, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
    ],
  },

  {
    subject: Subject.MATH1A,
    year: 2016,
    maxScore: 100,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 2, correctAnswer: null },
          { questionNumber: 2, score: 2, correctAnswer: null },
          { questionNumber: 3, score: 2, correctAnswer: null },
          { questionNumber: 4, score: 2, correctAnswer: null },
          { questionNumber: 5, score: 2, correctAnswer: null },
          { questionNumber: 6, score: 2, correctAnswer: null },
          { questionNumber: 7, score: 2, correctAnswer: null },
          { questionNumber: 8, score: 3, correctAnswer: null },
          { questionNumber: 9, score: 3, correctAnswer: null },
          { questionNumber: 10, score: 3, correctAnswer: null },
          { questionNumber: 11, score: 3, correctAnswer: null },
          { questionNumber: 12, score: 4, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 13, score: 3, correctAnswer: null },
          { questionNumber: 14, score: 3, correctAnswer: null },
          { questionNumber: 15, score: 3, correctAnswer: null },
          { questionNumber: 16, score: 3, correctAnswer: null },
          { questionNumber: 17, score: 3, correctAnswer: null },
          { questionNumber: 18, score: 3, correctAnswer: null },
          { questionNumber: 19, score: 3, correctAnswer: null },
          { questionNumber: 20, score: 3, correctAnswer: null },
          { questionNumber: 21, score: 2, correctAnswer: null },
          { questionNumber: 22, score: 2, correctAnswer: null },
          { questionNumber: 23, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 24, score: 3, correctAnswer: null },
          { questionNumber: 25, score: 3, correctAnswer: null },
          { questionNumber: 26, score: 3, correctAnswer: null },
          { questionNumber: 27, score: 3, correctAnswer: null },
          { questionNumber: 28, score: 4, correctAnswer: null },
          { questionNumber: 29, score: 4, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 30, score: 3, correctAnswer: null },
          { questionNumber: 31, score: 3, correctAnswer: null },
          { questionNumber: 32, score: 2, correctAnswer: null },
          { questionNumber: 33, score: 2, correctAnswer: null },
          { questionNumber: 34, score: 4, correctAnswer: null },
          { questionNumber: 35, score: 6, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 36, score: 2, correctAnswer: null },
          { questionNumber: 37, score: 3, correctAnswer: null },
          { questionNumber: 38, score: 3, correctAnswer: null },
          { questionNumber: 39, score: 3, correctAnswer: null },
          { questionNumber: 40, score: 3, correctAnswer: null },
          { questionNumber: 41, score: 2, correctAnswer: null },
          { questionNumber: 42, score: 2, correctAnswer: null },
          { questionNumber: 43, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
    ],
  },
  {
    subject: Subject.MATH1A,
    year: 2017,
    maxScore: 100,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 3, correctAnswer: null },
          { questionNumber: 2, score: 1, correctAnswer: null },
          { questionNumber: 3, score: 3, correctAnswer: null },
          { questionNumber: 4, score: 3, correctAnswer: null },
          { questionNumber: 5, score: 1, correctAnswer: null },
          { questionNumber: 6, score: 2, correctAnswer: null },
          { questionNumber: 7, score: 2, correctAnswer: null },
          { questionNumber: 8, score: 2, correctAnswer: null },
          { questionNumber: 9, score: 3, correctAnswer: null },
          { questionNumber: 10, score: 2, correctAnswer: null },
          { questionNumber: 11, score: 2, correctAnswer: null },
          { questionNumber: 12, score: 3, correctAnswer: null },
          { questionNumber: 13, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 14, score: 3, correctAnswer: null },
          { questionNumber: 15, score: 3, correctAnswer: null },
          { questionNumber: 16, score: 3, correctAnswer: null },
          { questionNumber: 17, score: 3, correctAnswer: null },
          { questionNumber: 18, score: 3, correctAnswer: null },
          { questionNumber: 19, score: 6, correctAnswer: null },
          { questionNumber: 20, score: 2, correctAnswer: null },
          { questionNumber: 21, score: 2, correctAnswer: null },
          { questionNumber: 22, score: 2, correctAnswer: null },
          { questionNumber: 23, score: 1, correctAnswer: null },
          { questionNumber: 24, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 25, score: 2, correctAnswer: null },
          { questionNumber: 26, score: 3, correctAnswer: null },
          { questionNumber: 27, score: 2, correctAnswer: null },
          { questionNumber: 28, score: 2, correctAnswer: null },
          { questionNumber: 29, score: 3, correctAnswer: null },
          { questionNumber: 30, score: 2, correctAnswer: null },
          { questionNumber: 31, score: 2, correctAnswer: null },
          { questionNumber: 32, score: 4, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 33, score: 2, correctAnswer: null },
          { questionNumber: 34, score: 2, correctAnswer: null },
          { questionNumber: 35, score: 2, correctAnswer: null },
          { questionNumber: 36, score: 2, correctAnswer: null },
          { questionNumber: 37, score: 3, correctAnswer: null },
          { questionNumber: 38, score: 2, correctAnswer: null },
          { questionNumber: 39, score: 2, correctAnswer: null },
          { questionNumber: 40, score: 2, correctAnswer: null },
          { questionNumber: 41, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 42, score: 3, correctAnswer: null },
          { questionNumber: 43, score: 3, correctAnswer: null },
          { questionNumber: 44, score: 3, correctAnswer: null },
          { questionNumber: 45, score: 3, correctAnswer: null },
          { questionNumber: 46, score: 2, correctAnswer: null },
          { questionNumber: 47, score: 3, correctAnswer: null },
          { questionNumber: 48, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
    ],
  },
  {
    subject: Subject.MATH1A,
    year: 2018,
    maxScore: 100,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 2, correctAnswer: null },
          { questionNumber: 2, score: 4, correctAnswer: null },
          { questionNumber: 3, score: 2, correctAnswer: null },
          { questionNumber: 4, score: 2, correctAnswer: null },
          { questionNumber: 5, score: 3, correctAnswer: null },
          { questionNumber: 6, score: 3, correctAnswer: null },
          { questionNumber: 7, score: 2, correctAnswer: null },
          { questionNumber: 8, score: 2, correctAnswer: null },
          { questionNumber: 9, score: 2, correctAnswer: null },
          { questionNumber: 10, score: 2, correctAnswer: null },
          { questionNumber: 11, score: 2, correctAnswer: null },
          { questionNumber: 12, score: 2, correctAnswer: null },
          { questionNumber: 13, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 14, score: 3, correctAnswer: null },
          { questionNumber: 15, score: 3, correctAnswer: null },
          { questionNumber: 16, score: 5, correctAnswer: null },
          { questionNumber: 17, score: 4, correctAnswer: null },
          { questionNumber: 18, score: 6, correctAnswer: null },
          { questionNumber: 19, score: 6, correctAnswer: null },
          { questionNumber: 20, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 21, score: 2, correctAnswer: null },
          { questionNumber: 22, score: 2, correctAnswer: null },
          { questionNumber: 23, score: 2, correctAnswer: null },
          { questionNumber: 24, score: 2, correctAnswer: null },
          { questionNumber: 25, score: 2, correctAnswer: null },
          { questionNumber: 26, score: 2, correctAnswer: null },
          { questionNumber: 27, score: 2, correctAnswer: null },
          { questionNumber: 28, score: 3, correctAnswer: null },
          { questionNumber: 29, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 30, score: 3, correctAnswer: null },
          { questionNumber: 31, score: 3, correctAnswer: null },
          { questionNumber: 32, score: 2, correctAnswer: null },
          { questionNumber: 33, score: 2, correctAnswer: null },
          { questionNumber: 34, score: 2, correctAnswer: null },
          { questionNumber: 35, score: 2, correctAnswer: null },
          { questionNumber: 36, score: 3, correctAnswer: null },
          { questionNumber: 37, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 38, score: 3, correctAnswer: null },
          { questionNumber: 39, score: 3, correctAnswer: null },
          { questionNumber: 40, score: 2, correctAnswer: null },
          { questionNumber: 41, score: 4, correctAnswer: null },
          { questionNumber: 42, score: 3, correctAnswer: null },
          { questionNumber: 43, score: 2, correctAnswer: null },
          { questionNumber: 44, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
    ],
  },

  {
    subject: Subject.MATH1A,
    year: 2019,
    maxScore: 100,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 2, correctAnswer: null },
          { questionNumber: 2, score: 2, correctAnswer: null },
          { questionNumber: 3, score: 2, correctAnswer: null },
          { questionNumber: 4, score: 2, correctAnswer: null },
          { questionNumber: 5, score: 2, correctAnswer: null },
          { questionNumber: 6, score: 2, correctAnswer: null },
          { questionNumber: 7, score: 2, correctAnswer: null },
          { questionNumber: 8, score: 2, correctAnswer: null },
          { questionNumber: 9, score: 2, correctAnswer: null },
          { questionNumber: 10, score: 2, correctAnswer: null },
          { questionNumber: 11, score: 2, correctAnswer: null },
          { questionNumber: 12, score: 2, correctAnswer: null },
          { questionNumber: 13, score: 2, correctAnswer: null },
          { questionNumber: 14, score: 2, correctAnswer: null },
          { questionNumber: 15, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 16, score: 4, correctAnswer: null },
          { questionNumber: 17, score: 3, correctAnswer: null },
          { questionNumber: 18, score: 2, correctAnswer: null },
          { questionNumber: 19, score: 3, correctAnswer: null },
          { questionNumber: 20, score: 3, correctAnswer: null },
          { questionNumber: 21, score: 3, correctAnswer: null },
          { questionNumber: 22, score: 3, correctAnswer: null },
          { questionNumber: 23, score: 4, correctAnswer: null },
          { questionNumber: 24, score: 1, correctAnswer: null },
          { questionNumber: 25, score: 1, correctAnswer: null },
          { questionNumber: 26, score: 1, correctAnswer: null },
          { questionNumber: 27, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 28, score: 2, correctAnswer: null },
          { questionNumber: 29, score: 2, correctAnswer: null },
          { questionNumber: 30, score: 3, correctAnswer: null },
          { questionNumber: 31, score: 2, correctAnswer: null },
          { questionNumber: 32, score: 2, correctAnswer: null },
          { questionNumber: 33, score: 3, correctAnswer: null },
          { questionNumber: 34, score: 3, correctAnswer: null },
          { questionNumber: 35, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 36, score: 3, correctAnswer: null },
          { questionNumber: 37, score: 2, correctAnswer: null },
          { questionNumber: 38, score: 3, correctAnswer: null },
          { questionNumber: 39, score: 3, correctAnswer: null },
          { questionNumber: 40, score: 2, correctAnswer: null },
          { questionNumber: 41, score: 2, correctAnswer: null },
          { questionNumber: 42, score: 2, correctAnswer: null },
          { questionNumber: 43, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 44, score: 4, correctAnswer: null },
          { questionNumber: 45, score: 3, correctAnswer: null },
          { questionNumber: 46, score: 3, correctAnswer: null },
          { questionNumber: 47, score: 2, correctAnswer: null },
          { questionNumber: 48, score: 2, correctAnswer: null },
          { questionNumber: 49, score: 3, correctAnswer: null },
          { questionNumber: 50, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
    ],
  },
  {
    subject: Subject.MATH1A,
    year: 2020,
    maxScore: 100,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 3, correctAnswer: null },
          { questionNumber: 2, score: 2, correctAnswer: null },
          { questionNumber: 3, score: 2, correctAnswer: null },
          { questionNumber: 4, score: 3, correctAnswer: null },
          { questionNumber: 5, score: 2, correctAnswer: null },
          { questionNumber: 6, score: 2, correctAnswer: null },
          { questionNumber: 7, score: 2, correctAnswer: null },
          { questionNumber: 8, score: 2, correctAnswer: null },
          { questionNumber: 9, score: 2, correctAnswer: null },
          { questionNumber: 10, score: 2, correctAnswer: null },
          { questionNumber: 11, score: 2, correctAnswer: null },
          { questionNumber: 12, score: 2, correctAnswer: null },
          { questionNumber: 13, score: 2, correctAnswer: null },
          { questionNumber: 14, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 15, score: 3, correctAnswer: null },
          { questionNumber: 16, score: 3, correctAnswer: null },
          { questionNumber: 17, score: 3, correctAnswer: null },
          { questionNumber: 18, score: 3, correctAnswer: null },
          { questionNumber: 19, score: 3, correctAnswer: null },
          { questionNumber: 20, score: 6, correctAnswer: null },
          { questionNumber: 21, score: 3, correctAnswer: null },
          { questionNumber: 22, score: 3, correctAnswer: null },
          { questionNumber: 23, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 24, score: 4, correctAnswer: null },
          { questionNumber: 25, score: 2, correctAnswer: null },
          { questionNumber: 26, score: 2, correctAnswer: null },
          { questionNumber: 27, score: 2, correctAnswer: null },
          { questionNumber: 28, score: 3, correctAnswer: null },
          { questionNumber: 29, score: 4, correctAnswer: null },
          { questionNumber: 30, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 31, score: 3, correctAnswer: null },
          { questionNumber: 32, score: 3, correctAnswer: null },
          { questionNumber: 33, score: 2, correctAnswer: null },
          { questionNumber: 34, score: 2, correctAnswer: null },
          { questionNumber: 35, score: 3, correctAnswer: null },
          { questionNumber: 36, score: 3, correctAnswer: null },
          { questionNumber: 37, score: 4, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 38, score: 2, correctAnswer: null },
          { questionNumber: 39, score: 2, correctAnswer: null },
          { questionNumber: 40, score: 2, correctAnswer: null },
          { questionNumber: 41, score: 4, correctAnswer: null },
          { questionNumber: 42, score: 4, correctAnswer: null },
          { questionNumber: 43, score: 2, correctAnswer: null },
          { questionNumber: 44, score: 4, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
    ],
  },
  {
    subject: Subject.MATH2B,
    year: 2015,
    maxScore: 100,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 1, correctAnswer: null },
          { questionNumber: 2, score: 1, correctAnswer: null },
          { questionNumber: 3, score: 1, correctAnswer: null },
          { questionNumber: 4, score: 1, correctAnswer: null },
          { questionNumber: 5, score: 2, correctAnswer: null },
          { questionNumber: 6, score: 2, correctAnswer: null },
          { questionNumber: 7, score: 1, correctAnswer: null },
          { questionNumber: 8, score: 2, correctAnswer: null },
          { questionNumber: 9, score: 1, correctAnswer: null },
          { questionNumber: 10, score: 3, correctAnswer: null },
          { questionNumber: 11, score: 3, correctAnswer: null },
          { questionNumber: 12, score: 3, correctAnswer: null },
          { questionNumber: 13, score: 2, correctAnswer: null },
          { questionNumber: 14, score: 2, correctAnswer: null },
          { questionNumber: 15, score: 2, correctAnswer: null },
          { questionNumber: 16, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 17, score: 2, correctAnswer: null },
          { questionNumber: 18, score: 2, correctAnswer: null },
          { questionNumber: 19, score: 1, correctAnswer: null },
          { questionNumber: 20, score: 3, correctAnswer: null },
          { questionNumber: 21, score: 1, correctAnswer: null },
          { questionNumber: 22, score: 3, correctAnswer: null },
          { questionNumber: 23, score: 4, correctAnswer: null },
          { questionNumber: 24, score: 5, correctAnswer: null },
          { questionNumber: 25, score: 2, correctAnswer: null },
          { questionNumber: 26, score: 2, correctAnswer: null },
          { questionNumber: 27, score: 2, correctAnswer: null },
          { questionNumber: 28, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 29, score: 2, correctAnswer: null },
          { questionNumber: 30, score: 1, correctAnswer: null },
          { questionNumber: 31, score: 2, correctAnswer: null },
          { questionNumber: 32, score: 2, correctAnswer: null },
          { questionNumber: 33, score: 1, correctAnswer: null },
          { questionNumber: 34, score: 1, correctAnswer: null },
          { questionNumber: 35, score: 1, correctAnswer: null },
          { questionNumber: 36, score: 3, correctAnswer: null },
          { questionNumber: 37, score: 2, correctAnswer: null },
          { questionNumber: 38, score: 3, correctAnswer: null },
          { questionNumber: 39, score: 1, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 40, score: 2, correctAnswer: null },
          { questionNumber: 41, score: 1, correctAnswer: null },
          { questionNumber: 42, score: 1, correctAnswer: null },
          { questionNumber: 43, score: 1, correctAnswer: null },
          { questionNumber: 44, score: 1, correctAnswer: null },
          { questionNumber: 45, score: 2, correctAnswer: null },
          { questionNumber: 46, score: 1, correctAnswer: null },
          { questionNumber: 47, score: 1, correctAnswer: null },
          { questionNumber: 48, score: 2, correctAnswer: null },
          { questionNumber: 49, score: 2, correctAnswer: null },
          { questionNumber: 50, score: 2, correctAnswer: null },
          { questionNumber: 51, score: 2, correctAnswer: null },
          { questionNumber: 52, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 53, score: 3, correctAnswer: null },
          { questionNumber: 54, score: 2, correctAnswer: null },
          { questionNumber: 55, score: 2, correctAnswer: null },
          { questionNumber: 56, score: 2, correctAnswer: null },
          { questionNumber: 57, score: 2, correctAnswer: null },
          { questionNumber: 58, score: 2, correctAnswer: null },
          { questionNumber: 59, score: 2, correctAnswer: null },
          { questionNumber: 60, score: 2, correctAnswer: null },
          { questionNumber: 61, score: 1, correctAnswer: null },
          { questionNumber: 62, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 6,
        questions: [
          { questionNumber: 63, score: 2, correctAnswer: null },
          { questionNumber: 64, score: 2, correctAnswer: null },
          { questionNumber: 65, score: 2, correctAnswer: null },
          { questionNumber: 66, score: 2, correctAnswer: null },
          { questionNumber: 67, score: 2, correctAnswer: null },
          { questionNumber: 68, score: 2, correctAnswer: null },
          { questionNumber: 69, score: 2, correctAnswer: null },
          { questionNumber: 70, score: 2, correctAnswer: null },
          { questionNumber: 71, score: 2, correctAnswer: null },
          { questionNumber: 72, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
    ],
  },
  {
    subject: Subject.MATH2B,
    year: 2016,
    maxScore: 100,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 2, correctAnswer: null },
          { questionNumber: 2, score: 2, correctAnswer: null },
          { questionNumber: 3, score: 1, correctAnswer: null },
          { questionNumber: 4, score: 1, correctAnswer: null },
          { questionNumber: 5, score: 1, correctAnswer: null },
          { questionNumber: 6, score: 1, correctAnswer: null },
          { questionNumber: 7, score: 2, correctAnswer: null },
          { questionNumber: 8, score: 2, correctAnswer: null },
          { questionNumber: 9, score: 2, correctAnswer: null },
          { questionNumber: 10, score: 1, correctAnswer: null },
          { questionNumber: 11, score: 3, correctAnswer: null },
          { questionNumber: 12, score: 2, correctAnswer: null },
          { questionNumber: 13, score: 2, correctAnswer: null },
          { questionNumber: 14, score: 2, correctAnswer: null },
          { questionNumber: 15, score: 2, correctAnswer: null },
          { questionNumber: 16, score: 1, correctAnswer: null },
          { questionNumber: 17, score: 1, correctAnswer: null },
          { questionNumber: 18, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 19, score: 2, correctAnswer: null },
          { questionNumber: 20, score: 3, correctAnswer: null },
          { questionNumber: 21, score: 3, correctAnswer: null },
          { questionNumber: 22, score: 2, correctAnswer: null },
          { questionNumber: 23, score: 3, correctAnswer: null },
          { questionNumber: 24, score: 2, correctAnswer: null },
          { questionNumber: 25, score: 1, correctAnswer: null },
          { questionNumber: 26, score: 2, correctAnswer: null },
          { questionNumber: 27, score: 2, correctAnswer: null },
          { questionNumber: 28, score: 2, correctAnswer: null },
          { questionNumber: 29, score: 3, correctAnswer: null },
          { questionNumber: 30, score: 3, correctAnswer: null },
          { questionNumber: 31, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 32, score: 2, correctAnswer: null },
          { questionNumber: 33, score: 2, correctAnswer: null },
          { questionNumber: 34, score: 2, correctAnswer: null },
          { questionNumber: 35, score: 2, correctAnswer: null },
          { questionNumber: 36, score: 2, correctAnswer: null },
          { questionNumber: 37, score: 2, correctAnswer: null },
          { questionNumber: 38, score: 4, correctAnswer: null },
          { questionNumber: 39, score: 4, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 40, score: 1, correctAnswer: null },
          { questionNumber: 41, score: 1, correctAnswer: null },
          { questionNumber: 42, score: 2, correctAnswer: null },
          { questionNumber: 43, score: 2, correctAnswer: null },
          { questionNumber: 44, score: 1, correctAnswer: null },
          { questionNumber: 45, score: 1, correctAnswer: null },
          { questionNumber: 46, score: 1, correctAnswer: null },
          { questionNumber: 47, score: 1, correctAnswer: null },
          { questionNumber: 48, score: 1, correctAnswer: null },
          { questionNumber: 49, score: 1, correctAnswer: null },
          { questionNumber: 50, score: 2, correctAnswer: null },
          { questionNumber: 51, score: 2, correctAnswer: null },
          { questionNumber: 52, score: 2, correctAnswer: null },
          { questionNumber: 53, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 54, score: 1, correctAnswer: null },
          { questionNumber: 55, score: 1, correctAnswer: null },
          { questionNumber: 56, score: 1, correctAnswer: null },
          { questionNumber: 57, score: 1, correctAnswer: null },
          { questionNumber: 58, score: 1, correctAnswer: null },
          { questionNumber: 59, score: 1, correctAnswer: null },
          { questionNumber: 60, score: 1, correctAnswer: null },
          { questionNumber: 61, score: 1, correctAnswer: null },
          { questionNumber: 62, score: 2, correctAnswer: null },
          { questionNumber: 63, score: 1, correctAnswer: null },
          { questionNumber: 64, score: 1, correctAnswer: null },
          { questionNumber: 65, score: 1, correctAnswer: null },
          { questionNumber: 66, score: 1, correctAnswer: null },
          { questionNumber: 67, score: 2, correctAnswer: null },
          { questionNumber: 68, score: 2, correctAnswer: null },
          { questionNumber: 69, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
    ],
  },
  {
    subject: Subject.MATH2B,
    year: 2017,
    maxScore: 100,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 3, correctAnswer: null },
          { questionNumber: 2, score: 2, correctAnswer: null },
          { questionNumber: 3, score: 3, correctAnswer: null },
          { questionNumber: 4, score: 3, correctAnswer: null },
          { questionNumber: 5, score: 2, correctAnswer: null },
          { questionNumber: 6, score: 2, correctAnswer: null },
          { questionNumber: 7, score: 2, correctAnswer: null },
          { questionNumber: 8, score: 2, correctAnswer: null },
          { questionNumber: 9, score: 2, correctAnswer: null },
          { questionNumber: 10, score: 3, correctAnswer: null },
          { questionNumber: 11, score: 2, correctAnswer: null },
          { questionNumber: 12, score: 2, correctAnswer: null },
          { questionNumber: 13, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 14, score: 2, correctAnswer: null },
          { questionNumber: 15, score: 1, correctAnswer: null },
          { questionNumber: 16, score: 2, correctAnswer: null },
          { questionNumber: 17, score: 1, correctAnswer: null },
          { questionNumber: 18, score: 1, correctAnswer: null },
          { questionNumber: 19, score: 1, correctAnswer: null },
          { questionNumber: 20, score: 2, correctAnswer: null },
          { questionNumber: 21, score: 2, correctAnswer: null },
          { questionNumber: 22, score: 3, correctAnswer: null },
          { questionNumber: 23, score: 3, correctAnswer: null },
          { questionNumber: 24, score: 3, correctAnswer: null },
          { questionNumber: 25, score: 3, correctAnswer: null },
          { questionNumber: 26, score: 3, correctAnswer: null },
          { questionNumber: 27, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 28, score: 2, correctAnswer: null },
          { questionNumber: 29, score: 2, correctAnswer: null },
          { questionNumber: 30, score: 2, correctAnswer: null },
          { questionNumber: 31, score: 3, correctAnswer: null },
          { questionNumber: 32, score: 2, correctAnswer: null },
          { questionNumber: 33, score: 2, correctAnswer: null },
          { questionNumber: 34, score: 2, correctAnswer: null },
          { questionNumber: 35, score: 2, correctAnswer: null },
          { questionNumber: 36, score: 2, correctAnswer: null },
          { questionNumber: 37, score: 1, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 38, score: 1, correctAnswer: null },
          { questionNumber: 39, score: 1, correctAnswer: null },
          { questionNumber: 40, score: 2, correctAnswer: null },
          { questionNumber: 41, score: 2, correctAnswer: null },
          { questionNumber: 42, score: 2, correctAnswer: null },
          { questionNumber: 43, score: 2, correctAnswer: null },
          { questionNumber: 44, score: 2, correctAnswer: null },
          { questionNumber: 45, score: 2, correctAnswer: null },
          { questionNumber: 46, score: 3, correctAnswer: null },
          { questionNumber: 47, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 48, score: 3, correctAnswer: null },
          { questionNumber: 49, score: 3, correctAnswer: null },
          { questionNumber: 50, score: 3, correctAnswer: null },
          { questionNumber: 51, score: 3, correctAnswer: null },
          { questionNumber: 52, score: 2, correctAnswer: null },
          { questionNumber: 53, score: 3, correctAnswer: null },
          { questionNumber: 54, score: 2, correctAnswer: null },
          { questionNumber: 55, score: 1, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
    ],
  },

  {
    subject: Subject.MATH2B,
    year: 2018,
    maxScore: 100,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 1, correctAnswer: null },
          { questionNumber: 2, score: 1, correctAnswer: null },
          { questionNumber: 3, score: 2, correctAnswer: null },
          { questionNumber: 4, score: 2, correctAnswer: null },
          { questionNumber: 5, score: 2, correctAnswer: null },
          { questionNumber: 6, score: 3, correctAnswer: null },
          { questionNumber: 7, score: 3, correctAnswer: null },
          { questionNumber: 8, score: 3, correctAnswer: null },
          { questionNumber: 9, score: 2, correctAnswer: null },
          { questionNumber: 10, score: 1, correctAnswer: null },
          { questionNumber: 11, score: 1, correctAnswer: null },
          { questionNumber: 12, score: 2, correctAnswer: null },
          { questionNumber: 13, score: 3, correctAnswer: null },
          { questionNumber: 14, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 15, score: 1, correctAnswer: null },
          { questionNumber: 16, score: 2, correctAnswer: null },
          { questionNumber: 17, score: 2, correctAnswer: null },
          { questionNumber: 18, score: 4, correctAnswer: null },
          { questionNumber: 19, score: 2, correctAnswer: null },
          { questionNumber: 20, score: 3, correctAnswer: null },
          { questionNumber: 21, score: 3, correctAnswer: null },
          { questionNumber: 22, score: 1, correctAnswer: null },
          { questionNumber: 23, score: 3, correctAnswer: null },
          { questionNumber: 24, score: 4, correctAnswer: null },
          { questionNumber: 25, score: 2, correctAnswer: null },
          { questionNumber: 26, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 27, score: 2, correctAnswer: null },
          { questionNumber: 28, score: 2, correctAnswer: null },
          { questionNumber: 29, score: 2, correctAnswer: null },
          { questionNumber: 30, score: 2, correctAnswer: null },
          { questionNumber: 31, score: 2, correctAnswer: null },
          { questionNumber: 32, score: 2, correctAnswer: null },
          { questionNumber: 33, score: 2, correctAnswer: null },
          { questionNumber: 34, score: 2, correctAnswer: null },
          { questionNumber: 35, score: 1, correctAnswer: null },
          { questionNumber: 36, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 37, score: 1, correctAnswer: null },
          { questionNumber: 38, score: 1, correctAnswer: null },
          { questionNumber: 39, score: 2, correctAnswer: null },
          { questionNumber: 40, score: 2, correctAnswer: null },
          { questionNumber: 41, score: 2, correctAnswer: null },
          { questionNumber: 42, score: 4, correctAnswer: null },
          { questionNumber: 43, score: 2, correctAnswer: null },
          { questionNumber: 44, score: 2, correctAnswer: null },
          { questionNumber: 45, score: 2, correctAnswer: null },
          { questionNumber: 46, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 47, score: 2, correctAnswer: null },
          { questionNumber: 48, score: 1, correctAnswer: null },
          { questionNumber: 49, score: 1, correctAnswer: null },
          { questionNumber: 50, score: 1, correctAnswer: null },
          { questionNumber: 51, score: 1, correctAnswer: null },
          { questionNumber: 52, score: 1, correctAnswer: null },
          { questionNumber: 53, score: 2, correctAnswer: null },
          { questionNumber: 54, score: 1, correctAnswer: null },
          { questionNumber: 55, score: 1, correctAnswer: null },
          { questionNumber: 56, score: 1, correctAnswer: null },
          { questionNumber: 57, score: 1, correctAnswer: null },
          { questionNumber: 58, score: 2, correctAnswer: null },
          { questionNumber: 59, score: 1, correctAnswer: null },
          { questionNumber: 60, score: 1, correctAnswer: null },
          { questionNumber: 61, score: 1, correctAnswer: null },
          { questionNumber: 62, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
    ],
  },
  {
    subject: Subject.MATH2B,
    year: 2019,
    maxScore: 100,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 1, correctAnswer: null },
          { questionNumber: 2, score: 2, correctAnswer: null },
          { questionNumber: 3, score: 2, correctAnswer: null },
          { questionNumber: 4, score: 3, correctAnswer: null },
          { questionNumber: 5, score: 3, correctAnswer: null },
          { questionNumber: 6, score: 2, correctAnswer: null },
          { questionNumber: 7, score: 2, correctAnswer: null },
          { questionNumber: 8, score: 2, correctAnswer: null },
          { questionNumber: 9, score: 2, correctAnswer: null },
          { questionNumber: 10, score: 2, correctAnswer: null },
          { questionNumber: 11, score: 2, correctAnswer: null },
          { questionNumber: 12, score: 1, correctAnswer: null },
          { questionNumber: 13, score: 1, correctAnswer: null },
          { questionNumber: 14, score: 1, correctAnswer: null },
          { questionNumber: 15, score: 2, correctAnswer: null },
          { questionNumber: 16, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 17, score: 1, correctAnswer: null },
          { questionNumber: 18, score: 1, correctAnswer: null },
          { questionNumber: 19, score: 1, correctAnswer: null },
          { questionNumber: 20, score: 2, correctAnswer: null },
          { questionNumber: 21, score: 1, correctAnswer: null },
          { questionNumber: 22, score: 2, correctAnswer: null },
          { questionNumber: 23, score: 2, correctAnswer: null },
          { questionNumber: 24, score: 2, correctAnswer: null },
          { questionNumber: 25, score: 2, correctAnswer: null },
          { questionNumber: 26, score: 3, correctAnswer: null },
          { questionNumber: 27, score: 2, correctAnswer: null },
          { questionNumber: 28, score: 1, correctAnswer: null },
          { questionNumber: 29, score: 2, correctAnswer: null },
          { questionNumber: 30, score: 3, correctAnswer: null },
          { questionNumber: 31, score: 3, correctAnswer: null },
          { questionNumber: 32, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 33, score: 2, correctAnswer: null },
          { questionNumber: 34, score: 2, correctAnswer: null },
          { questionNumber: 35, score: 2, correctAnswer: null },
          { questionNumber: 36, score: 3, correctAnswer: null },
          { questionNumber: 37, score: 1, correctAnswer: null },
          { questionNumber: 38, score: 3, correctAnswer: null },
          { questionNumber: 39, score: 2, correctAnswer: null },
          { questionNumber: 40, score: 2, correctAnswer: null },
          { questionNumber: 41, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 42, score: 1, correctAnswer: null },
          { questionNumber: 43, score: 1, correctAnswer: null },
          { questionNumber: 44, score: 1, correctAnswer: null },
          { questionNumber: 45, score: 1, correctAnswer: null },
          { questionNumber: 46, score: 1, correctAnswer: null },
          { questionNumber: 47, score: 1, correctAnswer: null },
          { questionNumber: 48, score: 1, correctAnswer: null },
          { questionNumber: 49, score: 1, correctAnswer: null },
          { questionNumber: 50, score: 1, correctAnswer: null },
          { questionNumber: 51, score: 2, correctAnswer: null },
          { questionNumber: 52, score: 1, correctAnswer: null },
          { questionNumber: 53, score: 2, correctAnswer: null },
          { questionNumber: 54, score: 2, correctAnswer: null },
          { questionNumber: 55, score: 2, correctAnswer: null },
          { questionNumber: 56, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 57, score: 2, correctAnswer: null },
          { questionNumber: 58, score: 2, correctAnswer: null },
          { questionNumber: 59, score: 2, correctAnswer: null },
          { questionNumber: 60, score: 2, correctAnswer: null },
          { questionNumber: 61, score: 2, correctAnswer: null },
          { questionNumber: 62, score: 2, correctAnswer: null },
          { questionNumber: 63, score: 2, correctAnswer: null },
          { questionNumber: 64, score: 2, correctAnswer: null },
          { questionNumber: 65, score: 2, correctAnswer: null },
          { questionNumber: 66, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
    ],
  },

  {
    subject: Subject.MATH2B,
    year: 2020,
    maxScore: 100,
    testStructure: [
      {
        section: 1,
        questions: [
          { questionNumber: 1, score: 2, correctAnswer: null },
          { questionNumber: 2, score: 2, correctAnswer: null },
          { questionNumber: 3, score: 3, correctAnswer: null },
          { questionNumber: 4, score: 2, correctAnswer: null },
          { questionNumber: 5, score: 2, correctAnswer: null },
          { questionNumber: 6, score: 2, correctAnswer: null },
          { questionNumber: 7, score: 2, correctAnswer: null },
          { questionNumber: 8, score: 3, correctAnswer: null },
          { questionNumber: 9, score: 2, correctAnswer: null },
          { questionNumber: 10, score: 2, correctAnswer: null },
          { questionNumber: 11, score: 2, correctAnswer: null },
          { questionNumber: 12, score: 2, correctAnswer: null },
          { questionNumber: 13, score: 2, correctAnswer: null },
          { questionNumber: 14, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 2,
        questions: [
          { questionNumber: 15, score: 2, correctAnswer: null },
          { questionNumber: 16, score: 2, correctAnswer: null },
          { questionNumber: 17, score: 2, correctAnswer: null },
          { questionNumber: 18, score: 2, correctAnswer: null },
          { questionNumber: 19, score: 3, correctAnswer: null },
          { questionNumber: 20, score: 2, correctAnswer: null },
          { questionNumber: 21, score: 2, correctAnswer: null },
          { questionNumber: 22, score: 3, correctAnswer: null },
          { questionNumber: 23, score: 3, correctAnswer: null },
          { questionNumber: 24, score: 3, correctAnswer: null },
          { questionNumber: 25, score: 3, correctAnswer: null },
          { questionNumber: 26, score: 3, correctAnswer: null },
        ],
        sectionTotal: { score: 30 },
      },
      {
        section: 3,
        questions: [
          { questionNumber: 27, score: 2, correctAnswer: null },
          { questionNumber: 28, score: 1, correctAnswer: null },
          { questionNumber: 29, score: 2, correctAnswer: null },
          { questionNumber: 30, score: 1, correctAnswer: null },
          { questionNumber: 31, score: 1, correctAnswer: null },
          { questionNumber: 32, score: 2, correctAnswer: null },
          { questionNumber: 33, score: 2, correctAnswer: null },
          { questionNumber: 34, score: 2, correctAnswer: null },
          { questionNumber: 35, score: 2, correctAnswer: null },
          { questionNumber: 36, score: 2, correctAnswer: null },
          { questionNumber: 37, score: 1, correctAnswer: null },
          { questionNumber: 38, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 4,
        questions: [
          { questionNumber: 39, score: 2, correctAnswer: null },
          { questionNumber: 40, score: 2, correctAnswer: null },
          { questionNumber: 41, score: 2, correctAnswer: null },
          { questionNumber: 42, score: 1, correctAnswer: null },
          { questionNumber: 43, score: 1, correctAnswer: null },
          { questionNumber: 44, score: 1, correctAnswer: null },
          { questionNumber: 45, score: 2, correctAnswer: null },
          { questionNumber: 46, score: 1, correctAnswer: null },
          { questionNumber: 47, score: 1, correctAnswer: null },
          { questionNumber: 48, score: 2, correctAnswer: null },
          { questionNumber: 49, score: 2, correctAnswer: null },
          { questionNumber: 50, score: 1, correctAnswer: null },
          { questionNumber: 51, score: 1, correctAnswer: null },
          { questionNumber: 52, score: 1, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
      {
        section: 5,
        questions: [
          { questionNumber: 53, score: 2, correctAnswer: null },
          { questionNumber: 54, score: 2, correctAnswer: null },
          { questionNumber: 55, score: 2, correctAnswer: null },
          { questionNumber: 56, score: 2, correctAnswer: null },
          { questionNumber: 57, score: 2, correctAnswer: null },
          { questionNumber: 58, score: 2, correctAnswer: null },
          { questionNumber: 59, score: 2, correctAnswer: null },
          { questionNumber: 60, score: 2, correctAnswer: null },
          { questionNumber: 61, score: 2, correctAnswer: null },
          { questionNumber: 62, score: 2, correctAnswer: null },
        ],
        sectionTotal: { score: 20 },
      },
    ],
  },
];
